package netdiag

import (
	"context"
	"net/http"
	"net/http/httptest"
	"reflect"
	"strings"
	"testing"
	"time"

	"ds2api/internal/config"
)

func TestParseResolvConf(t *testing.T) {
	fixture := `
# Generated by NetworkManager
nameserver 1.1.1.1
nameserver 8.8.8.8
nameserver 1.1.1.1 # duplicate
nameserver invalid.ip
# nameserver 9.9.9.9
nameserver 2606:4700:4700::1111
`
	expected := []string{"1.1.1.1", "8.8.8.8", "2606:4700:4700::1111"}
	got := parseResolvConf(fixture)
	if !reflect.DeepEqual(got, expected) {
		t.Fatalf("parseResolvConf = %v; want %v", got, expected)
	}
}

func TestParseWindowsIPConfig(t *testing.T) {
	fixture := `
Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : local
   Description . . . . . . . . . . . : Intel Ethernet
   Physical Address. . . . . . . . . : 00-11-22-33-44-55
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   IPv4 Address. . . . . . . . . . . : 192.168.1.100(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . : 192.168.1.1
   DNS Servers . . . . . . . . . . . : 192.168.1.1
                                       8.8.8.8
                                       2001:4860:4860::8888
   NetBIOS over Tcpip. . . . . . . . : Enabled
`
	expected := []string{"192.168.1.1", "8.8.8.8", "2001:4860:4860::8888"}
	got := parseWindowsIPConfig(fixture)
	if !reflect.DeepEqual(got, expected) {
		t.Fatalf("parseWindowsIPConfig = %v; want %v", got, expected)
	}
}

func TestParseScutilDNS(t *testing.T) {
	fixture := `
DNS configuration

resolver #1
  nameserver[0] : 1.1.1.1
  nameserver[1] : 1.0.0.1
  if_index : 4 (en0)
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records
  order    : 300000
`
	expected := []string{"1.1.1.1", "1.0.0.1"}
	got := parseScutilDNS(fixture)
	if !reflect.DeepEqual(got, expected) {
		t.Fatalf("parseScutilDNS = %v; want %v", got, expected)
	}
}

func TestCollectReportMocked(t *testing.T) {
	ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.Contains(r.URL.Path, "trace") {
			w.WriteHeader(http.StatusOK)
			_, _ = w.Write([]byte("ip=198.51.100.1\nloc=US\ncolo=SFO\n"))
			return
		}
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write([]byte("198.51.100.1"))
	}))
	defer ts.Close()

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	// Direct test of single platform
	client := ts.Client()
	status := checkSinglePlatform(ctx, client, platformTarget{
		Platform: "TestServer",
		URL:      ts.URL,
	})

	if status.Status != "reachable" {
		t.Errorf("status.Status = %s; want reachable", status.Status)
	}
	if status.HTTPStatus != http.StatusOK {
		t.Errorf("status.HTTPStatus = %d; want 200", status.HTTPStatus)
	}

	// Test CollectReport with empty proxy
	rep := CollectReport(ctx, &config.Proxy{})
	if rep.Timestamp == 0 {
		t.Errorf("rep.Timestamp is 0")
	}
}
